<a href="https://colab.research.google.com/github/Kritikargv17/Deep-Learning-LAB/blob/main/Exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    return x * (1 - x)

# 1. Single neuron for AND gate
def single_neuron_AND():
    print("=== Single Neuron for AND Gate ===")
    X = np.array([[0,0], [0,1], [1,0], [1,1]])
    y = np.array([[0], [0], [0], [1]])

    np.random.seed(1)
    weights = np.random.rand(2,1)
    bias = np.random.rand(1)

    lr = 0.1
    epochs = 10000

    for _ in range(epochs):
        # Forward pass
        z = np.dot(X, weights) + bias
        a = sigmoid(z)

        # Backpropagation
        error = y - a
        d_a = error * sigmoid_deriv(a)

        d_w = np.dot(X.T, d_a)
        d_b = np.sum(d_a)

        weights += lr * d_w
        bias += lr * d_b

    # Final predictions
    final_output = sigmoid(np.dot(X, weights) + bias)
    print("Predictions after training:")
    print(np.round(final_output))
    print()

# 2. Feedforward NN for XOR
def ffnn_XOR():
    print("=== FFNN for XOR Gate ===")
    X = np.array([[0,0], [0,1], [1,0], [1,1]])
    y = np.array([[0], [1], [1], [0]])

    np.random.seed(1)
    w0 = np.random.randn(2, 2)
    b0 = np.zeros((1, 2))
    w1 = np.random.randn(2, 1)
    b1 = np.zeros((1, 1))

    lr = 0.1
    epochs = 10000

    for _ in range(epochs):
        # Forward pass
        z1 = np.dot(X, w0) + b0
        a1 = sigmoid(z1)
        z2 = np.dot(a1, w1) + b1
        a2 = sigmoid(z2)

        # Backpropagation
        error = y - a2
        d_a2 = error * sigmoid_deriv(a2)

        d_w1 = np.dot(a1.T, d_a2)
        d_b1 = np.sum(d_a2, axis=0, keepdims=True)

        d_a1 = np.dot(d_a2, w1.T) * sigmoid_deriv(a1)
        d_w0 = np.dot(X.T, d_a1)
        d_b0 = np.sum(d_a1, axis=0)

        w1 += lr * d_w1
        b1 += lr * d_b1
        w0 += lr * d_w0
        b0 += lr * d_b0

    print("Predictions after training:")
    print(np.round(a2))
    print()

# 3. General Multilayer Perceptron (MLP) class
class MLP:
    def __init__(self, layers):
        np.random.seed(42)
        self.weights = []
        self.biases = []

        # Initialize weights and biases
        for i in range(len(layers) - 1):
            self.weights.append(np.random.randn(layers[i], layers[i+1]))
            self.biases.append(np.zeros((1, layers[i+1])))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_deriv(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.activations = [X]
        self.zs = []
        for w, b in zip(self.weights, self.biases):
            z = np.dot(self.activations[-1], w) + b
            a = self.sigmoid(z)
            self.zs.append(z)
            self.activations.append(a)
        return self.activations[-1]

    def backward(self, y, lr):
        error = y - self.activations[-1]
        delta = error * self.sigmoid_deriv(self.activations[-1])

        for i in reversed(range(len(self.weights))):
            a_prev = self.activations[i]
            dW = np.dot(a_prev.T, delta)
            dB = np.sum(delta, axis=0, keepdims=True)

            self.weights[i] += lr * dW
            self.biases[i] += lr * dB

            if i != 0:
                delta = np.dot(delta, self.weights[i].T) * self.sigmoid_deriv(self.activations[i])

    def train(self, X, y, epochs, lr):
        for _ in range(epochs):
            self.forward(X)
            self.backward(y, lr)

    def predict(self, X):
        return np.round(self.forward(X))

def test_mlp():
    print("=== MLP for XOR Gate ===")
    X = np.array([[0,0], [0,1], [1,0], [1,1]])
    y = np.array([[0], [1], [1], [0]])

    mlp = MLP([2, 4, 1])  # 2 inputs, 4 hidden neurons, 1 output

    mlp.train(X, y, epochs=10000, lr=0.1)

    print("Predictions after training:")
    print(mlp.predict(X))
    print()

# Main
if __name__ == "__main__":
    single_neuron_AND()
    ffnn_XOR()
    test_mlp()


=== Single Neuron for AND Gate ===
Predictions after training:
[[0.]
 [0.]
 [0.]
 [1.]]

=== FFNN for XOR Gate ===
Predictions after training:
[[0.]
 [1.]
 [1.]
 [0.]]

=== MLP for XOR Gate ===
Predictions after training:
[[0.]
 [1.]
 [1.]
 [0.]]

